### ISSUE TITLE
Tyres & Rims page: The two categories should be added at the same custom posts name at the backend.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Bridgestone-Service-Centre#30]
Tyres category and Rims category are currently implemented as separate Custom Posts name at the backend. Better to create one custom posts name then a taxonomy for the two categories should apply.
![image](https://cloud.githubusercontent.com/assets/11186304/6519539/644ab628-c3f0-11e4-9adb-6fd05adc9522.png)

**Comment by genesiscebudigital** [comment]
I confrom to stanley . , he preffer 1 custom post for tyres and 1 custom post for rims
