### ISSUE TITLE
Tyres & Rims page: Brand logo image should not be cropped and must be resized according to its dimension size specified on the design specs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Bridgestone-Service-Centre#37]
![image](https://cloud.githubusercontent.com/assets/11186304/6519953/6c344010-c3f6-11e4-82d9-1773ba6b1708.png)

**Comment by genesiscebudigital** [comment]
it is needed to crop the image because if the client upload to large images . , the site is very slow
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/image-sizes

**Comment by maluzynel** [comment]
As per standard: If images are logos / icons, ensure that it is not cropped and must be re-sized according to its’ aspect ratio.
