### ISSUE TITLE
All mobile devices: Page should not be zoomable/draggable.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Bridgestone-Service-Centre#57]
![image3](https://cloud.githubusercontent.com/assets/11186304/6521273/6be5dbfe-c410-11e4-9cb7-803bf95d778b.jpg)

**Comment by maluzynel** [comment]
Still draggable and zoomable.
![image](https://cloud.githubusercontent.com/assets/11186304/6570357/1e88881c-c734-11e4-9a02-2370fe09424f.png)

**Comment by genesiscebudigital** [comment]
Try to clear cache
