### ISSUE TITLE
Homepage - Leadins section: Leadins should limited to 3 items display only as per the design specs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Bridgestone-Service-Centre#77]
![image](https://cloud.githubusercontent.com/assets/11186304/6568776/952d4b2c-c718-11e4-9f03-e44c2f120568.png)

**Comment by maluzynel** [comment]
Displayed leadin items should be based on the menu attributes ascending order. Currently unable to display the new added leadin post.

**Comment by genesiscebudigital** [comment]
Try To Check all leadins attribute
