### ISSUE TITLE
Menu button: Menu label moves down and distorted in all mobile devices.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Bridgestone-Service-Centre#86]
![image](https://cloud.githubusercontent.com/assets/11186304/6570561/a3beaa18-c737-11e4-9759-6eecdec5d950.png)

**Comment by maluzynel** [comment]
Not yet fixed in iTouch 4 mobile device view.

**Comment by maluzynel** [comment]
Not yet fixed in iTouch mobile device view. Menu still moves down.
![image](https://cloud.githubusercontent.com/assets/11186304/6589227/a7ab115c-c7d7-11e4-8527-38c3e042da64.png)

**Comment by maluzynel** [comment]
Still moves down.

**Comment by genesiscebudigital** [comment]
try again . , sorry we don't have mobile device here . , I just trying to change my CSS structure , , hope it works
